function [u_vel, v_vel] = remove_divergence( ...
    u_vel, v_vel, dx, dy, x_num, y_num, k_mod, ghost ...
)

prior_divergence = velocity_divergence( ...
    u_vel, v_vel, dx, dy, x_num, y_num, ghost ...
);

press(ghost + 1:x_num + ghost, ghost + 1:y_num + ghost) = laplacian_solver( ...
    k_mod, prior_divergence ...
);

u_vel(ghost + 1:x_num + ghost - 1,ghost + 1:y_num + ghost) = ...
    u_vel(ghost + 1:x_num + ghost - 1,ghost + 1:y_num + ghost) ...
    - pressure_dx(press, dx, x_num, y_num, ghost);

v_vel(ghost+1:x_num+ghost,ghost+1:y_num+ghost-1) = ...
    v_vel(ghost+1:x_num+ghost,ghost+1:y_num+ghost-1) ...
    - pressure_dy(press, dy, x_num, y_num, ghost);

[u_vel, v_vel] = velocity_boundaries(u_vel, v_vel, x_num, y_num, ghost);

end