function [du_dt, dv_dt, dtheta_dt] = get_time_slope( ...
    u_vel, v_vel, theta, dx, dy, x_num, y_num, ghost ...
)

[uu_flux, vu_flux, uv_flux, vv_flux, ut_flux, vt_flux] = get_flux( ...
    u_vel, v_vel, theta, x_num, y_num, ghost ...
);

% M-2 X N-2
du_dt = -1 * ( ...
    (uu_flux(2:x_num, :) - uu_flux(1:x_num - 1, :)) / dx...
    + (vu_flux(:, 2:y_num + 1) - vu_flux(:, 1:y_num)) / dy...
);

% M-2 X N-2
dv_dt = -1 * ( ...
    (uv_flux(2:x_num + 1, :) - uv_flux(1:x_num, :)) / dx...
    + (vv_flux(:, 2:y_num) - vv_flux(:, 1:y_num - 1)) / dy...
);

% M-1 X N-1
dtheta_dt = -1 * ( ...
    (ut_flux(2:x_num + 1, :) - ut_flux(1:x_num, :)) / dx...
    + (vt_flux(:, 2:y_num + 1) - vt_flux(:, 1:y_num)) / dy...
);

end