function [du_dt, dv_dt] = get_time_slope( ...
    u_vel, v_vel, dx, dy, x_num, y_num, ghost ...
)

[uu_flux, vu_flux, uv_flux, vv_flux] = get_flux( ...
    u_vel, v_vel, x_num, y_num, ghost ...
);

% M-2 X N-2
du_dt = -1 * ( ...
    (uu_flux(2:x_num - 1, :) - uu_flux(1:x_num - 2, :)) / dx...
    + (vu_flux(:, 2:y_num) - vu_flux(:, 1:y_num - 1)) / dy...
);

% M-2 X N-2
dv_dt = -1 * ( ...
    (uv_flux(2:x_num, :) - uv_flux(1:x_num - 1, :)) / dx...
    + (vv_flux(:, 2:y_num - 1) - vv_flux(:, 1:y_num - 2)) / dy...
);

end