function du_dt = get_du_dt( ...
    u_vel, uu_flux, vu_flux, prandtl, dx, dy, x_num, y_num, ghost ...
)

% M-2 X N-1
% Convection Term
du_dt = -1 * ( ...
    (uu_flux(2:x_num, :) - uu_flux(1:x_num - 1, :)) / dx...
    + (vu_flux(:, 2:y_num + 1) - vu_flux(:, 1:y_num)) / dy...
);

floor_idx =  ghost + 1;
roof_idx = ghost + y_num;
u_dx_slice = u_vel(ghost:x_num + ghost, floor_idx:roof_idx);
u_dy_slice = u_vel(ghost + 1:x_num + ghost - 1, ghost:roof_idx + 1);

% Viscous term
du_dt = du_dt + prandtl * ( ...
    ( ...
        u_dx_slice(1:x_num - 1, :)  ...
        - 2 * u_dx_slice(2:x_num, :)  ...
        + u_dx_slice(3:x_num + 1, :) ...
    ) / dx ^ 2 ...
    + ( ...
        u_dy_slice(:, 1:y_num)  ...
        - 2 * u_dy_slice(:, 2:y_num + 1)  ...
        + u_dy_slice(:, 3:y_num + 2) ...
    ) / dy ^ 2 ...
);

end
